title: "Certifiable Robot Perception: from Global Optimization to Safer Robots"
description: Title
sitename: CertifiablePerception@RSS2020
baseurl: "/CertifiablePerception-RSS2020"
url: "https://mit-spark.github.io"

# Scholar
# ========================================================================================
scholar:
  style: apa
  locale: en
  sort_by: year, month
  order: descending
  source: ./
  bibliography: resources.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: false
  query: "@*"

plugins:
  - jekyll/scholar

sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Makefile
  - resources.bib
